# GitHub Sponsors & Funding Options for In Memoria
#
# In Memoria is economic infrastructure for sustainable AI-assisted development.
# Your support helps make AI coding more efficient and cost-effective for everyone.
#
# Token efficiency matters: As AI inference costs rise due to power/compute constraints,
# In Memoria's 93% token reduction architecture helps reduce costs across the entire ecosystem.

# GitHub Sponsors
github: [pi22by7]

# PayPal - One-time or recurring donations
custom: ["https://paypal.me/piyushairani", "https://github.com/pi22by7/in-memoria/blob/main/funding.json"]