name: 🐛 Bug Report
description: Report a bug in In-Memoria
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Run command...
        2. See error...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error output (if any)
      render: text
      placeholder: Paste error messages here...

  - type: input
    id: version
    attributes:
      label: Version
      placeholder: "0.5.6"
